server:
  port: ${SERVER_PORT:8081}

spring:
  application:
    name: subscriptions-backend

  datasource:
    url: ${DB_URL:jdbc:mysql://localhost:3306/subscription_backend?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
    username: ${DB_USERNAME:root}
    password: ${DB_PASSWORD:root}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    packages-to-scan: com.yourorg

  flyway:
    enabled: true
    baseline-on-migrate: true

cloudinary:
  cloud-name: ${CLOUDINARY_CLOUD_NAME:}
  api-key: ${CLOUDINARY_API_KEY:}
  api-secret: ${CLOUDINARY_API_SECRET:}
  folder: ${CLOUDINARY_FOLDER:subscription-csv}

app:
  auth:
    jwt-secret: ${JWT_SECRET:U3Vic2NyaXB0aW9uQmFja2VuZFNlY3JldEtleUZvclN0YWdlQW5kRGV2TW9kZQ==}
    jwt-expiration-minutes: ${JWT_EXPIRATION_MINUTES:1440}
